package com.orange.cloud.servicebroker.filter.securitygroups.filter;

import org.assertj.core.api.Assertions;
import org.junit.Test;

/**
 * @author Sebastien Bortolussi
 */
public class RuleDescriptionTest {

    @Test
    public void rule_description_value() throws Exception {

        final ImmutableRuleDescription ruleDescription = ImmutableRuleDescription.builder()
                .servicebindingId("service-binding-id")
                .serviceBrokerName("service-broker-name")
                .serviceInstanceName("service-instance-name")
                .build();

        Assertions.assertThat(ruleDescription.value())
                .isEqualTo("generated by sec group filter broker for service binding<service-binding-id> to allow access to service instance<service-instance-name> created from service broker<service-broker-name>.");

    }

}